server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: group-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  profiles:
    include: local

#  config:
#    import: "configserver:"
#  cloud:
#    config:
#      uri: http://223.130.152.189:8084
#      name: group-service