server:
  port: 8081

spring:
  application:
    name: user-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#
#  profiles:
#    include: db, route

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://223.130.152.189:8084
      name: user-service