eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}